server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog?currentSchema=polar_bookshop
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5

logging:
  level:
    root: info

openapi:
  oAuthFlow:
    tokenUrl: http://localhost:9000/realms/Microservices-demo-realm/protocol/openid-connect/token