apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9001"
    spec:
      containers:
        - name: catalog-service
          image: catalog-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            #- name: SECRET_JDBC_URL
              #valueFrom:
                #secretKeyRef:
                  #name: polar-postgres-catalog-credentials
                  #key: spring.datasource.url
            #- name: SECRET_JDBC_USERNAME
              #valueFrom:
                #secretKeyRef:
                  #name: polar-postgres-catalog-credentials
                  #key: spring.datasource.username
            #- name: SECRET_JDBC_PASSWORD
              #valueFrom:
                #secretKeyRef:
                  #name: polar-postgres-catalog-credentials
                  #key: spring.datasource.password
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9001
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9001
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
            - name: catalog-config-volume
              mountPath: /workspace/config
            #- name: postgres-credentials-volume
              #mountPath: /workspace/secrets/postgres
      volumes:
        - name: catalog-config-volume
          configMap:
            name: catalog-config
        #- name: postgres-credentials-volume
          #secret:
            #secretName: polar-postgres-catalog-credentials